PROJECT_DIR: './data/projects'

API_ADDRESS: 'http://127.0.0.1:5000'

API_ENDPOINTS:
    LOAD_PROJECTS: '/api/v1/projects'
    CREATE_PROJECT: '/api/v1/projects'
    DELETE_PROJECT: '/api/v1/projects/delete'
